markdown: rdiscount
permalink: /:title/
url: http://nevergiveupyang1989.net
name: nevergiveupyang1989.NET
author: yang1989
qq: 497384230
email: nevergiveupyang1989@gmail.com
duoshuo: yang1989
beian: ******
cnzz: 99999
weibo: ******
github: nevergiveupyang1989
pygments: true
safe: true
paginate: 20
about: "记录成长的点滴，用不放弃"
